# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :tests do
    gradle(
    task: "testDebugUnitTest"
    )
  end

  desc "Build App release bundle"
    lane :bundleAppRelease do
      gradle(
      task: "app:bundleRelease"
      )
    end

  desc "Upload AAB to Google Play internal track"
    lane :uploadColBundleToPlayStoreInternal do
      # Ensure environment variables are available
      ENV['PLAY_STORE_SERVICE_ACCOUNT_JSON'] ||= ''
      ENV['PACKAGE_NAME'] ||= ''

      # Write the service account JSON to a file
      File.open("google_play.json", "w") do |file|
        file.write(ENV['PLAY_STORE_SERVICE_ACCOUNT_JSON'])
      end

      supply(
        json_key: "google_play.json",
        package_name: ENV['PACKAGE_NAME'],
        aab: "app/build/outputs/bundle/colombiaRelease/app-colombia-release.aab",
        track: "internal",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft"
      )
    end

end
