name: Build release apk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Generate Gradle checksums
      run: |
          find "." -name "gradle.lockfile" -type f | sort | xargs shasum  > gradle-checksums.txt
          cat gradle-checksums.txt  

    - name: Setup gradlew cache
      uses: actions/cache@v3  
      with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('gradle-checksums.txt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ hashFiles('gradle-checksums.txt') }}-  

    - name: Setup local.properties
      env:
        APIURL: ${{ secrets.APIURL }}
        APPID: ${{ secrets.APPID }}          
        APIRESTKEY: ${{ secrets.APIRESTKEY }}
      run: |
          sed "s|APIRESTKEY|$APIRESTKEY|g; s|APPID|$APPID|g; s|APIURL|$APIURL|g" local.defaults.properties > local.properties
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
 
      run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

    - name: Install Fastlane
      run: |
        sudo gem install fastlane -NV
        
    - name: Run tests with Fastlane
      run: |
          fastlane tests

    - name: Build Release Bundle(aab)
      env:
         SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
         SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
         SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
         SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}      
      run: ./gradlew app:bundleRelease

    - name: Upload release .aab to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: colombiaRelease.aab
        path: app/build/outputs/bundle/colombiaRelease/app-colombia-release.aab

    - name: Run Fastlane to upload AAB to Google Play (internal track)
      env:
        PLAY_STORE_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
        SUPPLY_JSON_KEY_DATA: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
        PACKAGE_NAME: com.folklore.app.col
      run: |
        echo "$SUPPLY_JSON_KEY_DATA" > google_play.json
        fastlane run supply package_name:"$PACKAGE_NAME" json_key:"google_play.json" aab:"app/build/outputs/bundle/colombiaRelease/app-colombia-release.aab" track:"internal" skip_upload_metadata:true skip_upload_images:true skip_upload_screenshots:true release_status:"draft" 
    
